machty/ember-concurrency

package.json

https://github.com/testem/testem/releases/tag/v1.4.1 fixes for the previous seen issue.

Remove testem lock as the issue has been fixed

---

package.json
tests/acceptance/ember-data-test.js
tests/dummy/app/adapters/user.js
tests/dummy/app/data-test/controller.js
tests/dummy/app/data-test/template.hbs
tests/dummy/app/models/user.js
tests/dummy/app/router.js

trying (and failing so far) to replicate #26

add basic ember-data test

---

.travis.yml

See:
* https://docs.travis-ci.com/user/trusty-ci-environment/
* https://blog.travis-ci.com/2016-04-07-migration-update

Update Travis config to use GCE.

---

addon/-task-instance.js
tests/unit/task-instance-test.js

bugfix: handle arbitrary nestings of bubbling child task errors

---

addon/-task-group.js
addon/-task-property.js
addon/utils.js
tests/dummy/app/docs/examples/modal-fun/controller.js

polyfill Object.assign

---

addon/utils.js
config/ember-try.js

Fix `INVOKE` symbol location for glimmer2.
Fixes #63.

Enable testing against alpha builds.

---

addon/-task-property.js

- isRunning
- isQueued
- isIdle
- state
- last
- lastRunning
- lastPerformed
- lastSuccessful
- lastComplete
- lastErrored
- lastCanceled
- lastIncomplete

Add docs for Task members

---

addon/-task-property.js
tests/unit/task-test.js

fix error when overriding a task in subclass

---

addon/-task-property.js
tests/unit/task-test.js

allow tasks to be overridden by mocks and other arbitrary sets

---

addon/utils.js

This PR was generated automatically using ember-k-codemod

Remove deprecated Ember.K

---

.jsdoc
builddocs.sh
ember-cli-build.js
package.json

https://github.com/machty/ember-concurrency/issues/13
Currently pointing to my repo, while i work on getting my changes merged with the upstream repo

generate jsdocs on ember build

---

addon/helpers/cancel-all.js
addon/helpers/perform.js
addon/helpers/task.js
addon/initializers/ember-concurrency.js
app/helpers/cancel-all.js
app/helpers/perform.js
app/helpers/task.js
app/initializers/ember-concurrency.js

For: https://github.com/machty/ember-concurrency/issues/200

move app folder to addon folder and add reexports

---

tests/dummy/app/docs/encapsulated-task/template.hbs

"describes below" to "described below"

tiny typo fix

---

addon/-wait-for.js
addon/utils.js
tests/unit/wait-for-test.js

make waitFor yieldables compatible with promise helpers

---

addon/-task-instance.js
tests/unit/task-instance-test.js
tests/unit/task-test.js

Fix link to docs/task-cancelation-help

---

package-lock.json

Invalid character causes flow errors

Remove invalid character in package-lock.json

---

addon/-task-property.js
package-lock.json

Fix for https://github.com/machty/ember-concurrency/issues/261

Use class syntax for extending from ComputedProperty

---

tests/dummy/snippets/task-cancelation-example-3.js

This sample is used in the last bit on http://ember-concurrency.com/docs/task-cancelation-help

Update task-cancelation-example-3.js to use yield

---

.travis.yml
testem.js

Fight the mono culture, let's build with Firefox (too).

Build with Firefox (Too)

---

addon/-task-instance.js
addon/-task-property.js
tests/unit/deprecations-test.js
tests/unit/task-test.js

fix: #237 - replacing `Ember.Logger` with `console`

---

CONTRIBUTING.md
addon/-task-property.js

Update CONTRIBUTING markdown to include how to view generated API docs

Document task.cancelAll() options. 

---

addon/-scheduler.js
addon/utils.js
config/ember-try.js
package.json
tests/acceptance/root-test.js
tests/integration/no-render-breaking-test.js
yarn.lock

(Hopefully) Fixes #337 🤞 
Draft until there's a reproducible test case

Avoid using incrementProperty to workaround duplicate auto-tracking assertion in Ember 3.15

---

addon/-wait-for.js
addon/utils.js
tests/unit/wait-for-test.js

Add support for waitForEvent with 'on' API

---

addon/-wait-for.js
tests/unit/wait-for-test.js

Fix waitForProperty on non-EmberObject hosts

---

API.md
addon/-cancelable-promise-helpers.js
addon/index.js
tests/unit/cancelable-promise-helpers-test.js

Does this work? If not, I'd like to ask for this feature to be supported.

add hashSettled equivalent

---

addon/-task-property.js
addon/index.d.ts
tests/types/ember-concurrency-test.ts

* Adds types for `hashSettled`
* Adds types for `linked()` and `unlinked()` for `AbstractTask`

Add missing types

---

addon/-private/task-factory.js
tests/unit/task-property-test.js

In lieu of a better public API for this, add some code to provide fallback to TaskProperty prototype extensions for unknown decorator options.
This ensures `ember-concurrency-test-waiters`, `ember-concurrency-retryable`, etc. are still usable with the built-in decorators.

v2: Add shim to maintain decorator compatiblity with TaskProperty prototype extensions as options

---

.github/workflows/ci.yml
API.md
README.md
UPGRADING-2.x.md
addon/-private/external/yieldables.js
addon/-private/task-instance.js
addon/-private/task-properties.js
addon/-private/utils.js
addon/-private/wait-for.js
addon/index.d.ts
builddocs.sh
package.json
yarn.lock

Fix some missing jsdoc documentation, bump dev dependencies on ember-concurrency-async and ember-concurrency-ts, and ensure CI runs for new v1 branch (in case of backports, bugfixes, etc.)

v2 release finalization

---

addon/-private/external/scheduler/state-tracker/state.js
tests/unit/derived-state/on-state-test.js
tests/unit/task-states-test.js

.lastRunning resets one-by-one as tasks are completed, successfully or not

---

addon/index.d.ts
tests/types/ember-concurrency-test.ts

Expose lastValue decorator in TS definitions

---

UPGRADING-2.x.md

Document that @lastValue does not support chained property access

---

addon/-private/task.js
tests/unit/encapsulated-task-test.js

While TaskInstance state was exposed externally via proxying, the proxy was not used internally making TaskInstance state impossible to access. Fixes an issue reported in Discord.

Expose TaskInstance state inside encapsulated tasks

---

addon/-private/ember-environment.js

Fix inefficient use of run.once by EmberEnvironment.async

---

addon/-private/external/task-decorators.js
addon/-private/task-decorators.js

Further reducing amount of Ember-specific stuff

Move task decorators into external module

---

.github/workflows/ci.yml
CHANGELOG.md
addon/-private/task-public-api.js
tests/acceptance/helpers-test.js
tests/helpers/helpers.js
tests/integration/async-arrow-task-test.js

Add runtime assertion that async fn transpiled

---

addon/index.d.ts
tests/types/ember-concurrency-test.ts

Fix missing dropTask/etc types

---

index.js

Fix babel transform conflicts with ember-cli-code-coverage
