README.md
embeconcurrency.com redirects to ember-concurrency.com, so I figured we should just point folks there initially...
=> Update README.md to point to ember-concurrency.com

package.json, tests/acceptance/root-test.js, tests/helpers/module-for-acceptance.js
I missed this when I updated to Ember 2.3.0.  Also added a super simple silly acceptance test that would have caught this...
=> Bring back ember-load-initializers.

.gitignore, addon/index.js, package.json, yuidoc.json
This adds the following commands:
```
ember ember-cli-yuidoc
ember serve --docs
```
Both commands will emit YUIDoc generated JSON and HTML output in `./docs` folder, which can then be published to the website if desired.
There are a number of themes that we can investigate to make the default generated HTML nice enough to include on the site, but in the meantime fleshing out the actual API docs is a great way to make the code base more accessible to newbs (like myself)...
=> Enable YUIDoc generation.

tests/dummy/app/docs/task-function-syntax/template.hbs
Super tiny contribution but thought I'd fix it since I noticed this typo :)
let's = let us
lets = allows
Thanks for making such a cool piece of software :v:
=> small doc grammar fix

index.js
When using ember-concurrency in an addon that is consumed by another app, `this.app` is undefined. Passing in the `app` from the `included` hook to ensure that we've got an app when `this.app` fails. 
This may be limited to earlier versions of ember-cli, as I found the issue while using ember-cli 1.13.13.
@rwjblue
=> fix _findApp by passing in app from included hook

addon/-task-instance.js, addon/index.js, tests/dummy/app/components/my-button/component.js, tests/unit/error-handling-test.js, tests/unit/task-instance-test.js
Previously, if you had something like
```js
try {
yield someChildTask().perform();
} catch(e) {
// ...
}
```
and someChildTask (or the outer task) was canceled,
the catch block would run and you'd be responsible
for differentiating between a cancelation and another
kind of error thrown from someChildTask. This commit
changes these semantics as follows:
1. if you are within a task and you yield another
(child) task, if the outer task or the child
task is canceled, then any `catch` blocks
within the hierarchy of canceled tasks will
NOT run. In other words, it does not make
sense to test if an error in a catch block
is a TaskCancelation, because TaskCancelations
will never hit catch blocks
2. That said, if you call `.then` or `.catch`
on a `task.perform()`, then any TaskCancelations
WILL be …
=> No longer handle cancelation in catch blocks, add didCancel

API.md, addon/-yieldables.js, addon/index.js, tests/unit/yieldables-test.js
This adds allSettled as an available yieldable operation for the issue #74
=> Adding allSettled to yieldable operations

tests/dummy/app/components/start-task-example/component.js
- Helps clarify where the timeout method is being imported from for first time users implementing their first task
At first I thought adding a comment with a prefix of `//NOTE: ` would help, but thinking it through - I believe exposing the whole script would make it clearer for those looking to just try out the task without having to reference the API.
=> Clarify timeout method usage

addon/-property-modifiers-mixin.js, addon/-task-property.js, tests/unit/decorators-test.js
If you do ` task(...).maxConcurrency(n)` without applying any other modifier it's not really obvious what the intent is and has led to some confusion. In an effort to clear things up this PR will make it so that a warning (possibly signaling a deprecation) is logged in this scenario.
I created two new flags in the `-property-modifiers-mixin`. One is to track if a modifier was set and the other to track if `maxConcurrency()` was called. Then, in the `setup` hook I check to see if `maxConcurrency()` was called without setting a modifier. If it was I log a warning.
=> [Issue #77] maxConcurrency called without specifying a task modifier

tests/dummy/app/docs/examples/loading-ui/template.hbs
Noticed that the reigning used wasn't the one intended. And then noticed we had a very long run-on sentence 😀 
Greatly appreciate all your work here ... ❤️
=> Small grammatical tweaks

addon/-task-property.js, package.json
Recent changes to ember-getowner-polyfill make it a true polyfill.
This lets us ship the polyfill to only environments that need it, and reduce
boilerplate code in addons.
The refactor is basically just:
```js
import { getOwner } from 'ember-getowner-polyfill';
// ....snip....
getOwner(someThing);
```
To:
```js
import Ember from 'ember';
const { getOwner } = Ember;
// ....snip....
getOwner(someThing);
```
=> Update to ember-getowner-polyfill@1.1.0.

addon/-task-group.js, tests/unit/task-groups-test.js
`isRunning` on a TaskGroup returns an `Ember.computed.or` of two integers. Unfortunately, `Ember.computed.or` performs `||` which does not guarantee a `boolean`, so this leads to this truth table for `numRunning` and `numQueued`:
```
| numRunning | numQueued | isRunning |
|------------|-----------|-----------|
| 0          | 0         | 0         |
| 1          | 0         | 1         |
| 0          | 1         | 1         |
| 1          | 1         | 1         |
| 2          | 1         | 2         |
| 1          | 2         | 1         |
| ...        | ...       | ...       |
```
This PR changes this to:
```
| numRunning | numQueued | isRunning |
|------------|-----------|-----------|
| 0          | 0         | false     |
| 1          | 0         | true      |
| 0          | 1 …
```
=> Make TaskGroup.isRunning also return a boolean

addon/-decorators.js, tests/unit/task-property-test.js
=> machty+Bendemboski: task fn wrapper

CHANGELOG.md, addon/-task-instance.js, tests/unit/task-instance-test.js
This PR adds two more derived properties to TaskInstances:
`isSuccessful`: true if the task fulfills, that is it completes without error or cancelling.
`isError`: true if the task resolves to a rejection
=> Add isSuccessful and isError to TaskInstance

addon/index.js, addon/utils.js
EC has `ember-maybe-import-regenerator` since 0.7.5, the generator function is provided by default. We can remove the generator testing code.
=> remove unnecessary assertion

config/ember-try.js, package.json
This adds back ember-1.13 support
=> Adds ember-1.13 back to ember-try

tests/dummy/app/docs/controller.js, tests/dummy/app/docs/index/route.js, tests/dummy/app/docs/introduction/template.hbs, tests/dummy/app/router.js, tests/dummy/app/styles/app.scss
- created new route `introduction` & moved the template from `index` to `introduction`
- removed `underline` style from links
- added `active` style (bold + underline) on side-menu links
=> [docs] add active style on side menu

tests/dummy/app/application/controller.js, tests/dummy/app/application/template.hbs, tests/dummy/app/styles/app.scss
Added addon's version in the docs so people can notice that which version they're on. That would be great if there's a select box to choose docs by different versions. Baby steps!
=> [docs] show addon version in docs

addon/-cancelable-promise-helpers.js, tests/unit/cancelable-promise-helpers-test.js
Similarly to how it's very nice to be able to pass a mix of promises and simple values to Ember.RSVP.{hash,all}, it's nice to be able to pass a mix of task results and simple values to ember-concurrency's hash() and all() helpers. However, if one of these values were null or undefined, the cancellation code would throw an error. This fixes that.
=> Support null/undefined values in cancelable promise helpers

package.json, yarn.lock
This is upsetting a lot `ember-cli-dependency-lint`, as all other addons on my app are using 2.0.0
=> Bump getOwner polyfill

app/helpers/cancel-all.js, app/helpers/perform.js, app/helpers/task.js
related to https://github.com/machty/ember-concurrency/pull/170#issuecomment-318778569 😞 
proper solution is to just reexport stuff in the `app` folder and have the real code in the `addon` folder, but reverting that part should be enough for now.
=> Revert "New Module Imports" in "app" folder

addon/-helpers.js, addon/-task-instance.js, addon/-task-property.js, app/helpers/cancel-all.js, app/helpers/perform.js, package.json, tests/unit/task-test.js, yarn.lock
Fixes #161 
This PR detects the dreaded ["self-cancel loop/footgun"](https://github.com/machty/ember-concurrency/issues/161) and `console.warn`s that you need to use `someTask.linked().perform()` or `someTask.unlinked().perform()` to annotate how you want it to behave.
Aside from annotating the desired behavior in the case of the above footgun, `.linked()` doesn't actually do anything different than a normal `yield someTask.perform()`, and will warn you if you try and use it without immediately returning/yielding.
But `.unlinked()` on the other hand has use cases beyond fixing self-cancel loops. Semantically, the following are equivalent:
```
yield this.get('aTask').unlinked().perform()
yield Promise.resolve(this.get('aTask').perform());
```
Which is to say: "wait for this task instance …
=> Allow tasks to be specified as linked or unlinked

addon/index.js
Added basic explanation to `TaskGroup` JsDoc.
Issue #195
=> Added TaskGroup documentation

addon/-wait-for.js, addon/utils.js, tests/dummy/app/docs/controller.js, tests/dummy/app/docs/events/controller.js, tests/dummy/app/docs/events/template.hbs, tests/unit/wait-for-test.js
Closes #180.
Also removes `.on()` from the assertion message, as it was not supported.
=> feat(wait-for/event): support native DOM EventTargets

addon/-wait-for.js, addon/index.js, tests/unit/wait-for-test.js
This uses observes to wait for properties to
become a certain value before execution continues.
=> Add waitForProperty()

addon/-wait-for.js, tests/unit/wait-for-test.js
Prior to this commit, if you wanted to wait for
a property to equal a certain value, you had to
pass in something like `(v) => v === expectedValue`
as the third arg. With this commit, you can just
pass in `expectedValue` (so long as it isn't
a function) and it'll automatically create the
predicate function for you.
So instead of
```
yield waitForProperty(this, 'foo', (v) => v === 3);
```
you can just do
```
yield waitForProperty(this, 'foo', 3);
```
=> Enhance waitForProperty to allow passing in value to match against

package.json, yarn.lock
Was pointing at 5fae5bded7ecb16243e456e1f3611ebaf71562d9, which seems to have been removed, probably via rebase on upstream, [as Ed's PR is pending](https://github.com/ember-fastboot/ember-cli-fastboot/pull/546).
Also updates broccoli-asset-rev to 2.7.0, which [incorporates the changes from Ed's fork](https://github.com/rickharrison/broccoli-asset-rev/pull/125).
=> Update ember-cli-fastboot git ref to fix yarn install

addon/-task-instance.js
The page no longer uses `#` routing.
=> Fix link to task cancellation help page

addon/-task-property.js
Addresses the missing `TaskProperty` docs mentioned in #225
=> Add missing doc reference for `evented()` modifier

addon/-task-property.js
Hey @machty 
I don't have much experience with the documentation comments but it looks like the `evented` modifier documentation is using the `drop()` modifier. I added the `Evented` Mixin as well because it seems to be required.
could be possible to add something in the modifier function to add the Evented mixin to the object if it is used?
Something like: 
```js
//https://github.com/machty/ember-concurrency/blob/04226b7634d5dfa0628d64eae48b11b3e0cdbf35/addon/-property-modifiers-mixin.js#L48
evented() {
// not sure if there is a reliable way to check if the Mixin was mixed before 
if (isBlank(this.trigger)) {
this.reopen(Evented);
}
this._hasEnabledEvents = true;
return this;
},
``` 
Best regards,
Daniel.
=> fix: Add evented modifier to evented documentation and use Evented mixin in the example as well

tests/dummy/app/docs/derived-state/template.hbs
`isSuccessful` and `isError` are TaskInstance properties, not Task properties. I can confirm this is confusing because I just spent 15 minutes debugging to find out `myTask.isSuccessful` doesn't work...
=> Fix task vs task instance properties

app/helpers/cancel-all.js, app/helpers/perform.js, app/helpers/task.js, app/initializers/ember-concurrency.js
This removes reexports of things that don't actually exist.
There isn't a good reason to reexport these things in the app's namespace anyway. If people want access to these functions they should import directly from the ember-concurrency namespace.
I noticed this issue because I'm experimenting with better automatic dependency traversal, and these cases generate warnings.
=> Remove reexports of nonexistent names

addon/-task-property.js, tests/unit/task-test.js
Root cause of issue:
https://github.com/emberjs/ember.js/commit/246435e7260f45d9e5cc35a4a8b4de4f011f3625
The above commit started making use of the previously
unused Descriptor#setup method that e-c uses
for setting up observers and e-c wasn't calling
the super method, which was causing the ES5
getter to not be set on the object.
This commit calls the super `setup` method if it
exists so that Object.defineProperty is properly
called.
/cc @bendemboski
=> Fix ES5 getter syntax on Ember Canary

addon/-scheduler.js, addon/-task-property.js, addon/-task-state-mixin.js, addon/helpers/cancel-all.js, tests/unit/task-test.js
This is a first attempt at https://github.com/machty/ember-concurrency/issues/243.
This change includes two changes:
1. Change the signature of `cancelAll(reason)` to `cancelAll({ reason })`
It was stated in https://github.com/machty/ember-concurrency/issues/243#issuecomment-424844648 that it would probably be ok to change this without backwards compatibility. However, if there's a desire to have backwards compatibility, it wouldn't be hard to add.
Also note that I changed this signature for both the `cancelAll` on the scheduler as well as the task property. It isn't actually necessary to change the signature on the scheduler, but it seemed worth being consistent there. Again, let me know if you have a strong opinion :man_shrugging: 
2. Add a `resetState` option to …
=> cancelAll({ resetState: true }) can remove existing derived state

README.md
As I started working on #253, I noticed a few things in the README that didn't seem right. Here are a couple of random updates the README for things that I noticed.
* Remove `bower install`
It looks like `bower.json` was removed in 554e5c48bdf883f53e2792fe22aaef79282b2f71. It doesn't make sense to instruct potential maintainers to run `bower install`.
This was clearly something from the original blueprint that was missed when removing jQuery/bower. I think most maintainers know what to do but it's nice to have the README be more accurate to prevent confusion for a newer contributor.
* Update the running tests section
Running `yarn test` did not run `ember try:each`, as stated, so I updated the example. Is there an opinion as to which way potential contributors should be running tests? I'm …
=> Update readme for more accuracy

addon/-cancelable-promise-helpers.js
Fixes the link to the "Awaiting Multiple Child Tasks" example. Clicking it currently redirects to http://ember-concurrency.com/docs/introduction/
=> Fix links to docs

tests/dummy/app/docs/task-concurrency/template.hbs
This PR adds IDs to the headings of the subsections, so that hey can be directly linked to, like:
[`http://ember-concurrency.com/docs/task-concurrency#restartable`](http://ember-concurrency.com/docs/task-concurrency#restartable)
It also unifies the spelling style for the task modifiers in headings and copy text.
=> docs(task-concurrency): add IDs to headings, unify spelling

addon/-task-property.js
When you create a task manually using `set(obj, 'myTask', task(function*(){})` and then `perform` it the error message is misleading. This is the same issue as the deprecation added recently to computed properties, so I've used the same deprecation warning.
=> correct error message for later versions of Ember

addon/-task-group.js, addon/-task-property.js, addon/index.js, package.json, yarn.lock
We just landed some pretty major changes to the Descriptor system
upstream. We verified that ember-concurrency would still be able to work
first, this branch is that work. We should likely update it to use
`ember-compatibility-helpers` as well, so you can continue to support
older versions of Ember at the same time.
=> [BUGFIX] Updates internals for Ember Canary

tests/dummy/snippets/task-cancelation-example-1.js, tests/dummy/snippets/task-cancelation-example-2.js, tests/dummy/snippets/task-cancelation-example-3.js
The task name is `queryServer`, but `fetchResults` was referencing `doStuff`
=> Use correct task name in snippets

CONTRIBUTING.md, README.md
This PR moves information about how to contribute away from README.md to a new CONTRIBUTING.md
=> moving contribution guide to CONTRIBUTING.md

.travis.yml, README.md, config/ember-try.js
As discussed in #290 this reverts the dropped support for older Ember versions and their test matrix in that PR to cover all the previously supported Ember versions, which were starting at 2.4. 
Although the Readme's badge (which was broken) stated support for Ember 1.13, but tests failed for that version. Didn't dig into it, but updated (fixed) the badge with Ember 2.4 as the minimum supported and tested version. Agree?
=> Revert Ember support

addon/utils.js
When writing tests that fake time with `lolex` it complains:
> Cannot clear timer: timer created with setTimeout() but cleared with clearInterval()
There is no clear reason for using `clearInterval()` here for something that was created with `setTimeout()`. Using `clearTimeout()` instead seems more straight forward and would solve this issue.
---
Unrelated: I noticed that `rawTimeout()` is undocumented and not exported from the top-level file. Is there a reason for that? Is it not supposed to be used?
=> utils/rawTimeout: Use `clearTimeout()` instead of `clearInterval()`

package.json, yarn.lock
Currently when `yarn install`ing in this repo the following warning will
be issued:
warning ember-concurrency@1.0.0: "dependencies" has dependency "ember-maybe-import-regenerator" with range "^0.1.5" that collides with a dependency in "devDependencies" of the same name with version "^0.1.6"
I took a wild guess and assumed we should update the `"dependencies"`
version to match the most recent change.
Note that #315 should probably be merged first, and this rebased on top of it.
=> Resolve `ember-maybe-import-regenerator` Conflict

addon/-cancelable-promise-helpers.js, package.json, tests/unit/cancelable-promise-helpers-test.js, yarn.lock
Fixes #182.
FWIW `ember-cli-sass` / `node-sass` was giving me a major headache on my MacBook. I had to run as `yarn --ignore-scripts` to prevent the native `node-sass` build and then had to temporarily remove `ember-cli-sass` from the `package.json` in order to be able to start the test server.
I hope I didn't fuck up the `yarn.lock`. 😅 
<sup><sup>frankly, Sass needs to die in a fire... 🔥 </sup></sup>
=> feat(promise-helpers): assert that argument is an array

addon/-wait-for.js, tests/unit/wait-for-test.js
I ran into an issue, where `waitForQueue()` would never resolve. After some digging, I found out it was because I used `waitForQueue('sync')`, but the `sync` runloop was removed in 3.11. However, this was totally swallowed by `waitForQueue`, although e.g. `schedule('sync', func)` _did_ actually throw a descriptive error.
This PR fixes this by ensuring that an error thrown bubbles up correctly.
=> Ensure waitForQueue throws on errors

ember-cli-build.js, package.json, yarn.lock
Upgrades these dependencies:
- `ember-cli-sass`: `^7.1.3` -> `^10.0.1`
This allows running the dummy app with Node 12.
- `ember-cli-babel`: `^6.8.2` -> `^7.7.3`
This enables the usage of decorators.
Also removes the deprecated `babel.blacklist` config. This is now handled via the browser `targets.js`.
These were the only dependencies blocking my local development, but I would also recommend to upgrade the others soon:
=> chore(deps): upgrade ember-cli-sass & ember-cli-babel

addon/-task-property.js, tests/dummy/app/task-injection-test/controller.js
This fixes an issue with service injection inside
of encapsulated tasks on Ember 3.13+ by ensuring
tasks that are children of other tasks are
assigned a container to use for service injection.
=> Ensure tasks are assigned to a container

addon/-property-modifiers-mixin.js
When using a TaskGroup on an octane glimmer component `get` does not
exist on the component. Ember.get shields us from this and just works.
Fixes machty/ember-concurrency-decorators#57
=> Use ember get in case object isn't an EmberObject

addon/index.js, addon/utils.js, tests/dummy/app/testing-ergo/foo-settimeout/controller.js
`rawTimeout` was previously only available from `ember-concurrency/utils`. This PR promotes it to be available from the top-level module.
=> Export `rawTimeout` from `ember-concurrency` module 

addon/-scheduler.js, addon/-task-state-mixin.js
I missed some of these in #321. Though only the one in `-task-state-mixin.js ` seems to be an issue for my application, I didn't see the harm in protecting the others as well.
I did a walk through of all other instances of `.get()` not on `this` and these were the last ones I could find.
=> Use ember get for ES Classes

addon/-cancelable-promise-helpers.js, addon/-task-instance.js, addon/-wait-for.js, addon/utils.js, tests/unit/buffering-test.js, tests/unit/cancelable-promise-helpers-test.js
The refactor addresses some gaps between yieldable implementations
around how cancelation is handled, especially when used with cancelable promise helpers.
Resolves #308, #329
=> Refactor yieldable cancelation to work with cancelable promise helpers

tests/dummy/app/docs/testing-debugging/template.hbs
As raised in #328, the link is no longer active. Since 2016,
browser support for generators is quite good (caniuse has it at ~93%).
The need for the regenerator is relegated primarily
to IE11, which by default is only enabled for production builds
in the default Ember-CLI configuration.
Resolves #328
=> Remove regenerator docs that link to an old article

addon/utils.js, package.json, tests/acceptance/helpers-test.js, tests/dummy/app/helpers-test/controller.js, tests/dummy/app/helpers-test/template.hbs, yarn.lock
Builds on @thiagofelix's find in #312 (which fixes for 3.1 - 3.10ish), and adds the latest paths for `INVOKE` to work with 3.11+  and some tests for use with `action` and `fn` helpers
=> Fix use of tasks w/ action and fn helpers on 3.11+

addon/utils.js
The PR #67 fixed the `INVOKE` symbol for glimmer2 by adding `'ember-glimmer/helpers/action'` as one possible location where such constant can be find, starting on **ember@3.1.0** this location is no longer valid. 
I was able to trace the ember PR [#16291](https://github.com/emberjs/ember.js/pull/16291) that stoped exporting the INVOKE symbol from the file above.
The correct place to find the INVOKE symbol now should be from the `ember-glimmer` package (root package, not the sub module).
The problem I am having is trying to use ember-concurrency with ember@3.1.x version, the INVOKE symbol is not being found.
Ember Twiddle displaying the problem:
**Issue with ember@3.1.0**:
https://ember-twiddle.com/9fcee21b1dc407e4d61139bd7b2858b5
**Working well with ember@3.0.0**: …
=> Add `ember-glimmer` to locations where `INVOKE` symbol can be find.

tests/dummy/app/components/task-function-syntax-5/component.js, tests/dummy/app/docs/task-function-syntax/template.hbs
Raised in issue #271, there is currently no official documentation
on using ember-concurrency with native classes and other Octane-related
use-cases.
This adds a brief section to "Task Function Syntax" in the docs that
shows an example of use with a Glimmer component and mentions the
ember-concurrency-decorators addon as a more concise approach to the
default decorators via the task() property.
Thanks @jenweber for the Glimmer example!
=> Add some brief documentation on use with Octane/decorators

tests/dummy/app/components/task-function-syntax-5/component.js, tests/dummy/app/docs/task-function-syntax/template.hbs
As found in #343, `@computed` is required for native getters that access derived state on Tasks.
=> Add documentation around use of @computed

addon/index.js
Also, it returns a `TaskGroupProperty`, not a `TaskGroup`.
=> `taskGroup` does not take a `taskFn`

addon/index.d.ts, tests/types/ember-concurrency-test.ts
A `Task` is an `EmberObject`:
https://github.com/machty/ember-concurrency/blob/d066cd71a9e6abb8c749d931e971004a9930c587/addon/-task-property.js#L53-L55
This is important because the task state properties are computed properties, e.g.
https://github.com/machty/ember-concurrency/blob/d066cd71a9e6abb8c749d931e971004a9930c587/addon/-task-state-mixin.js#L14-L22
and require using `.get()` to access them in Ember < 3.1.
Update: `TaskInstance` and `TaskGroup` are also `EmberObject`s so I've included them as well.
@chancancode @dfreeman @chriskrycho
=> Types: Make Task, TaskInstance, and TaskGroup extend EmberObject

addon/-private/computed-properties.js, addon/-private/utils.js, addon/-private/wait-for.js, tests/unit/wait-for-test.js
Cherry-picks #348, #352, and #358 into `v2`, leaving TypeScript type definitions the only thing not yet ported to `v2`
=> v2: bugfixes from 1.1.6 - 1.2.0

addon/-private/ember-environment.js, addon/-private/external/scheduler/policies/execution-states.js, addon/-private/external/scheduler/refresh.js, addon/-private/external/task-instance/executor.js, addon/-private/external/task/taskable.js, addon/-private/task-group.js, addon/-private/task-instance.js, addon/-private/task.js, addon/-private/taskable-mixin.js, addon/-private/tracked-state.js, package.json, tests/integration/tracked-use-test.js, yarn.lock
This is a PR to use `@tracked` for `Task` and `TaskInstance` state on Ember 3.16+ to enable use without using `@computed` when consuming derived state.
In Ember < 3.16, e-c behaves as it currently does requiring `@computed` to track task-derived state changes.
This PR essentially replaces the state properties on the Ember implementations of `Task` and `TaskInstance` with those properties decorated with `@tracked` (done dynamically, though w/ property descriptors. not redefining them with actual decorator syntax, so there's no dependency on decorator transforms.) This incurs a little bit of a cost, since it's redefining the properties, but practically shouldn't have much effect since it's applied to the `Task` and `TaskInstance` prototypes, rather than every instance, so it would only be …
=> [v2] Use @tracked underneath on Ember 3.16+

addon/-cancelable-promise-helpers.js, addon/-task-property.js, config/ember-try.js, tests/acceptance/helpers-test.js, tests/dummy/app/helpers-test/template.hbs, tests/integration/helpers/invokable-action-test.js, tests/types/ember-concurrency-test.ts
This feature unfortunately depends on private APIs that will be removed in Ember 3.25. Unfortunately, the mechanism was already removed in Ember 3.20, making it impossible to support this for releases at least until recent canaries where it was re-introduced with a deprecation. However, the feature is rarely used, only documented in the changelog, and frequently breaks whenever the private constant it depends on moves modules internally throughout new versions of Ember.
It will continue to remain available for Ember < 3.20, but will not be available in Ember-Concurrency 2.0, and will show a deprecation warning from 1.3.0 forward.
Also, fixes the failing TypeScript tests, affecting other in-progress PRs #365 & #368
=> Deprecate direct usage of task with action helper and disable tests for it on 3.20+

tests/dummy/app/docs/examples/route-tasks/template.hbs
Small docs change. PR https://github.com/machty/ember-concurrency/pull/317 changed the `detail-route.js` snippet but didn't update the corresponding section of the docs. This is that snippet:
https://github.com/machty/ember-concurrency/blob/2be69e87280e7302c0ccfbb21b3884bc04db376f/tests/dummy/app/docs/examples/route-tasks/detail/route.js#L5-L34
=> docs: Replace cancelOn with cancelAll in route-tasks

addon/-private/external/task/taskable.js, addon/-private/tracked-state.js, tests/unit/task-groups-test.js, tests/unit/task-states-test.js
state on Task or TaskGroup indicates whether the task is
running or idle. We were setting this properly, but the
underlying property wasn't tracked, rendering it useless
in the template (breaking some docs pages)
=> v2: Make sure task/group-level state field is tracked

addon/-private/task.js, tests/acceptance/task-injection-test.js, tests/dummy/app/task-injection-test/controller.js, tests/dummy/app/task-injection-test/template.hbs
This one is a bit in-the-weeds, but it's effectively
a bugfix plus a workaround for < 3.16. We're now wrapping
TaskInstance internally and externally for EncapsulatedTask
launched instances. This is so that internal state updates
work. However, for Ember < 3.16, we needed to go a step
further and add some additional handlers to the Proxy setup
in order to ensure derived state updates get rendered
correctly, due to the way the state was stored in those
versions.
=> Fix encapsulated state render updates

addon/-private/task-decorators.js, addon/-private/task-factory.js, addon/-private/task-instance.js, addon/-private/task-properties.js, addon/-task-property.js, addon/index.d.ts, addon/index.js, jsconfig.json, package.json, tests/dummy/app/components/task-function-syntax-5/component.js, tests/helpers/helpers.js, tests/integration/tracked-use-test.js, tests/types/ember-concurrency-test.ts, tests/unit/decorators-test.js, tests/unit/derived-state/on-state-test.js, tests/unit/encapsulated-task-test.js, tests/unit/generator-method-test.js, tests/unit/last-value-test.js, tests/unit/task-groups-test.js, tests/unit/task-test.js, tests/unit/wait-for-test.js, tsconfig.json
Supersedes #384 
This provides built-in support for the "nice" decorator syntax based on the decorators implemented at [`ember-concurrency-decorators`](https://github.com/machty/ember-concurrency-decorators). Many thanks to @buschtoens for years of stewardship of that addon, and important contributions from @chancancode for TypeScript support, and others in the community to get it to a place where it's seen wide adoption in the world of Ember Octane, TypeScript, and native ES classes.
The "ugly" decorators (e.g. (`@(task(function* () { ... }).drop()`) will remain available by virtue of coming "for free" with the computed-based `TaskProperty` implementation (necessary to support the classic EmberObject model for task hosts), but will be deprecated in favor of these "nice" decorators at …
=> v2: Integrate "nice" decorators from ember-concurrency-decorators

README.md, UPGRADING-2.x.md, tests/dummy/app/application/controller.js, tests/dummy/app/docs/controller.js, tests/dummy/app/docs/installation/template.hbs, tests/dummy/app/docs/task-decorators/template.hbs, tests/dummy/app/docs/testing-debugging/template.hbs, tests/dummy/app/router.js, tests/dummy/snippets/last-value-decorator.js, tests/dummy/snippets/task-decorators-1.js, tests/dummy/snippets/task-decorators-2.js, tests/dummy/snippets/task-decorators-3.js, tests/dummy/snippets/task-decorators-4.js, tests/dummy/snippets/task-decorators-5.js, tests/dummy/snippets/task-group-decorators-1.js, tests/dummy/snippets/task-group-decorators-2.js, tests/dummy/snippets/task-group-decorators-3.js, tests/dummy/snippets/ts/broken.ts
Last piece of the [ember-concurrency-decorators](https://github.com/machty/ember-concurrency-decorators) merge for v2. It's more or less a copy of the README from that project with some minor tweaks and reorganization of some FAQ stuff
=> v2: Add decorator docs from ember-concurrency-decorators

UPGRADING-2.x.md, package.json, tests/unit/e-c-decorators-test.js, yarn.lock
Since we still want to maintain compatibility w/ ember-concurrency-decorators (for addons that need to work w/ both v1 and v2), we should test for compatibility still.
=> v2: Add test for interop w/ ember-concurrency-decorators

UPGRADING-2.x.md, addon/-private/external/scheduler/scheduler.js, addon/-private/external/task-instance/cancelation.js, addon/-private/external/task-instance/executor.js, addon/-private/external/task/taskable.js, addon/index.d.ts, tests/dummy/app/helpers-test/template.hbs, tests/types/ember-concurrency-test.ts, tests/unit/task-test.js
Cancelation is async, but cancel and cancelAll have not returned promises to enable awaiting cancelation. This PR changes that so the two can be used with async/await and/or Promises to ensure consuming applications can reliably schedule subsequent operations that may depend on cancelation
For example,
```javascript
@dropTask *myTask() {
while(1) {
console.log("hello!");
yield timeout(1000);
}
}
@task *restartMyTask() {
// Note the `yield`. This could also be an `await` or `then` outside of tasks
yield this.myTask.cancelAll();
// Without being able to `yield` on `cancelAll` above, the cancelation wouldn't be guaranteed to have taken place before this is called, resulting in `perform` no-oping and dropping the task and myTask would not restart
this.myTask.perform();
}
```
=> v2: Make cancel & cancelAll awaitable

addon/-private/task.js, tests/unit/encapsulated-task-test.js
It was inadvertently removed when re-implementing encapsulated
tasks with Proxy. However, it's a useful feature for implementing
sort-of "higher-order tasks" and since there's no viable replacement,
this PR reintroduces it. It is, however, considered intimate,
undocumented API that will not be covered under SemVer guarantees.
Because it can be read from `this`, it can be accidentally overwritten
by user code. A future solution might be to provide some sort of
`getHostContext()` yieldable to provide the value within task execution
and avoid the need to access it directly.
For now, restoring it will allow folks who depended on such undocumented
behavior to upgrade to 2.0.0.
=> Restore access to host context from encapsulated tasks

addon/-private/cancelable-promise-helpers.js, addon/-private/external/task-instance/executor.js, addon/-private/external/yieldables.js, tests/unit/cancelable-promise-helpers-test.js
=> Prevent synchronous errors in cancelable promise helpers from being rethrown asynchronously later

.jsdoc, API.md, CONTRIBUTING.md, addon/-private/task-decorators.js, addon/-private/task-group.js, addon/-private/task-instance.js, addon/-private/task-properties.js, addon/-private/task.js, addon/index.d.ts, builddocs.sh, jsconfig.json, package.json, yarn.lock
In moving stuff around, some methods such as `cancelAll` got lost in the jsdoc documentation. Went through and made sure all public API was adequately documented in jsdoc.
h/t @Turbo87 for the heads up on the `cancelAll` and @bendemboski who noticed `onState` hadn't been documented
=> Add missing jsdoc documentation

addon/-private/ember-environment.js, addon/-private/external/task-instance/executor.js, addon/-private/helpers.js, ember-cli-build.js, package.json, tests/dummy/app/helpers/swallow-error.js, tests/integration/helpers/perform-test.js, tests/unit/error-handling-test.js, yarn.lock
Wrapping `perform` in a full runloop means that a synchronous task throw will be
reported within that same invocation, before another helper is able to wrap and
instrument the task instance. Since it's already run, it's too late to do things
like attaching catch handlers. We do not need this runloop binding anymore, since
there's no auto-run assertion with the versions supported by ember-concurrency
2.x.
Fixes #409
=> Remove runloop binding for perform helper

addon/-private/external/yieldables.js, addon/-private/task-instance.js, addon/-private/task.js, addon/-private/utils.js, addon/-private/wait-for.js, addon/index.d.ts, addon/index.js, rfcs/0000-yieldables.md, tests/types/ember-concurrency-test.ts, tests/unit/cancelable-promise-helpers-test.js
[Rendered](https://github.com/machty/ember-concurrency/blob/mf-public_yieldable/rfcs/0000-yieldables.md)
Implementation is included as well, which shows refactor of built-in Yieldables to use the new API. Refactoring (or similar) will probably stand, regardless of whether to promote to public API, as calling `taskInstance.proceed` with various magic values in a bunch of places is error prone.
=> RFC: Public Yieldables API

addon/-private/external/scheduler/refresh.js, addon/-private/external/scheduler/state-tracker/state-tracker.js, addon/-private/external/scheduler/state-tracker/state.js, tests/unit/task-states-test.js
Covered by the included test case based on #422.
Given a bounded scheduler policy that drops running
task instances, if there's an immediate return in
via a later perform call, the state update from the earlier
task instance may get applied later than the task instance
with the immediate return.
Applied a similar approach that Glimmer uses, which is an
incrementing tag, by which we will track which state updates
are still valid. Anything after the last applied tag will be valid
and state updates from before will be ignored.
=> Avoid applying states out of order

addon/-private/external/scheduler/refresh.js, addon/-private/external/scheduler/state-tracker/state-tracker.js
In a spot of immediate post-merge regret on #423, I realized that refresh tags probably need to be segmented by tasks
=> Seperate refresh tags per-taskable

addon/-private/cancelable-promise-helpers.js, tests/acceptance/helpers-test.js, tests/dummy/app/helpers/color.js, tests/dummy/app/helpers/progress-style.js, tests/unit/cancelable-promise-helpers-test.js
Bug found in #413
Yieldables themselves can be triggered multiple times and return a different promise everytime they're casted, which Promise/RSVP.all, allSettled, race, etc. will do internally, but prevents collecting the disposer to use for cancelation. This effectively neutralizes cancellation, which is not what we want, so we need to cast it before handing it off to the Promise/RSVP implementation.
=> Cast Yieldables to promises when using cancelable promise helpers

config/ember-try.js, ember-cli-build.js, package.json, tests/integration/no-render-breaking-test.js, yarn.lock
This configures `ember-concurrency` to run the test suite against Embroider builds using the recommended approach (the `@embroider/test-setup` package).
This is an alternative to the approach taken in #368, which achieves the same goal manually; the package essentially does the same thing, but we abstract the "how" away to Embroider itself (which makes us more resilient to changes).
I configured the two Embroider jobs to allow failures, so that getting them to actually _work_ can be done outside of the process of just seeing whether they pass or not.
=> Configure `@embroider/test-setup`

addon/-private/external/scheduler/scheduler.js, addon/-private/external/task-factory.js, addon/-private/external/task/task.js, addon/-private/external/task/taskable.js, addon/-private/task-decorators.js, addon/-private/task-factory.js, addon/-private/task-properties.js, addon/-private/task.js
Some internal refactoring to separate the Ember bits of `TaskFactory`. This will provide some groundwork for a future RFC.
=> Extract generic TaskFactory base class

addon/helpers/perform.js, tests/integration/helpers/perform-test.js
Allows setting to reporting function for reporting to error handlers, etc. Also allows setting to `null` to swallow all errors. This is useful when using the `(perform)` helper with tasks that are always having their error states handled in the UI. In these cases, errors being raised either may be surfaced in the UI and the render errors will be extraneous or there's a desire to log directly to an error reporting service.
Fixes #435
=> Add onError parameter to perform helper

addon/-private/external/environment.js, addon/-private/external/task-factory.js, addon/-private/external/task/task.js, addon/-private/external/task/taskable.js, addon/-private/task-factory.js, addon/-private/task.js
Moves the `Task` perform logic into the `external` module and provides a real generic `Environment` implementation
=> Genericize task perform

addon/-private/external/task-decorators.js, tests/unit/decorators-test.js
Closes #481
It seems #457 removed a call to `_setupEmberKVO`, which was causing observers (and probably some other cases) to stop working.
=> Fix observers in 2.3.0+

tests/dummy/app/docs/tutorial/refactor/template.hbs
Addresses a small typo in the documentation that omitted the `this`.
=> Fix typo in documentation

lib/babel-plugin-transform-ember-concurrency-async-tasks.js
Closes #483
Even though the previous work on this (#490) correctly added a babel plugin ordering constraint, we were getting trolled by ordering conflicts due to how to Babel runs plugins visitors as it traverses the AST tree, which basically works like:
```
function traverseNodes(node) {
ORDERED_BABEL_PLUGINS.forEach(plugin => {
plugin.visitIfVisitorDeclared(node)
})
// recurse
node.children.forEach(n => traverseNodes(n));
}
```
In other words, given an AST node, it'll go through each plugin in order and let that plugin `visit` the node if it has a visitor declared. Some babel plugins are implemented by defining a number of NodeType visitors, but Istanbul's plugin only defines a visitor for the root Program node and then deeply traverses the tree, and because, prior to this PR, the Ember …
=> Babel: deeply traverse as early as possible

UPGRADING-2.x.md
just fixing a typo of the word "use"
=> Fix typo in UPGRADING guide

package.json, tests/dummy/app/application/controller.js, tests/dummy/app/application/template.hbs, tests/dummy/app/docs/examples/route-tasks/detail/route.js, tests/dummy/app/docs/examples/route-tasks/template.hbs, tests/dummy/app/services/notifications.js, tests/dummy/app/styles/app.scss, yarn.lock
We were only using this for the route-tasks page in the docs. Removing this to easy EC refactors now and in the future.
New treatment:
=> Remove (dummy-app only) dependency on ember-notify

package.json
Both versions are EOL: https://endoflife.date/nodejs
=> Drop Node 10/12

package.json
EOL is in less than 30 days, so going to drop official support now with the next major release of ember-concurrency
=> Drop Node 14

tests/dummy/app/components/code-snippet/template.hbs, tests/dummy/app/styles/app.scss
Follow up to #522.
Cleaning up the styling of code blocks now that ember-prism is used.
Before: 
After:
=> Improve styling of code blocks on documentation site

package.json, yarn.lock
Something (probably a release of new embroider packages) caused most of the floating dependencies scenarios to start failing in all branches. It looks like it was some kind of mismatch between the version of `@embroider/macros` used by `@ember/render-modifiers` (a dependency of `ember-prism`) and whatever version of `@embroider/shared-internals` it was finding in the `node_modules` tree.
So this commit updates us to the latest `@embroider/macros`, which allows us to dedupe `@embroider/macros` and `@embroider/shared-internals`, which appears to fix the issue.
=> Fix CI build

tests/dummy/app/docs/typescript/template.hbs
- Link to v2.3.0 and v2.3.2 as they both have important information
- Removes one TODO :)
=> docs: Insert link to release notes wrt taskFor() deprecation

.github/workflows/ci.yml, package.json, tests/dummy/config/ember-try.js, yarn.lock
fix #541
- allow ember 5 as peerDependency
- add ember-try scenarios for ember lts 4.8, 4.12 & ember 5.0
=> Add ember 5 as peerDependencies

tests/dummy/app/docs/tutorial/refactor/template.hbs
Just fixing a legacy syntax typo to reflect the actual diffs.
=> Fix typo in refactor tutorial

README.md
Since all the examples use arrow syntax, it makes sense to introduce the babel transform earlier.
The information is available in the upgrade docs, but this makes it more prominent by putting it in the installation instructions.
This might cut down on issues like #562
=> Add babel transform configuration to installation instructions

packages/test-app/snippets/ts/basic-example.ts, packages/test-app/snippets/ts/template-import-example.txt
Currently, all three ts-snippets had different ways of importing `Component`:
https://github.com/machty/ember-concurrency/blob/8e0c0379d6fa99a38c137ddd16345c60ebd3abba/packages/test-app/snippets/ts/basic-example.ts#L1
https://github.com/machty/ember-concurrency/blob/8e0c0379d6fa99a38c137ddd16345c60ebd3abba/packages/test-app/snippets/ts/template-import-example.txt#L1
https://github.com/machty/ember-concurrency/blob/8e0c0379d6fa99a38c137ddd16345c60ebd3abba/packages/test-app/snippets/ts/typing-task.ts#L1
The third one is the "standard" way, from the [ember guides](https://guides.emberjs.com/release/components/component-state-and-actions/#toc_tracked-properties), so I changed the first two to align with that.
=> Simplify ts snippets by using the same import statements for `import Component from `@glimmer/component`

packages/ember-concurrency/app/helpers/cancel-all.js, packages/ember-concurrency/app/helpers/perform.js, packages/ember-concurrency/app/helpers/task.js
Probably an oversight during the v1 -> v2 conversion?
=> Remove re-exports for helpers

packages/ember-concurrency/src/-private/task-properties.js, packages/ember-concurrency/src/-private/task-public-api.js
Deprecate any dependency on Computed Properties (the concept and the classic / constructor), which includes the classic `fooTask: task(function * () }` syntax. This means ECv5 will require any class with EC tasks to be converted to ES6 (tasks on `Component.extend`-ed components won't be supported any longer).
Also remove reference to non-existent `_setComputedDecorator`
=> Deprecate classic task(), rm setComputed
